AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 15

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  Safe: true
  SafeAutoCorrect: true
